### ISSUE TITLE
Cannot register with SSO

### ISSUE THREAD

**Issue by darrylcauldwell** [vmware/nsxansible#3]
When calling the nsx_sso_registration.py I get failure.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'ssoConfig'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1465395145.84-26105136860738/nsx_sso_registration\", line 2099, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1465395145.84-26105136860738/nsx_sso_registration\", line 80, in main\n    sso_reg['ssoConfig']['ssoAdminUsername'] = module.params['sso_admin_username']\nKeyError: 'ssoConfig'\n", "module_stdout": "\u001b[91mDEPRECATION WARNING: This method is deprecated in nsxramlclient v2.x and will be removed in future.\nPlease start using the method extract_resource_body_example instead.\nThis method does not support the NSXv 6.2.4 and later RAML specs\u001b[0m\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by yfauser** [comment]
That is likely because you are using the nsxramlclient 2.0.0 version with the newest version of the RAML spec. Unfortunately the newest versions of the RAML spec on the master branch of /nsxraml introduced a breaking change when switching to 'real' schemas using xsd. Therefore the nsxramlclient was changed to use the examples in the RAML spec instead of the schemas. We did not update the Ansible modules yet. I'll push a version with the changes soon in nsxansible. As a quick fix to unblock you you can use the nsxramlclient 1.0.4 version alongside with the RAML spec in the '6.2.2' or '6.1.6' branch of nsxraml.

**Comment by darrylcauldwell** [comment]
Thanks Yves,  reverting to nsxraml 6.2.2 branch and installing nsxramlclient 1.0.4,  worked a treat and sso now registers correctly

**Comment by darrylcauldwell** [comment]
pip install nsxramlclient==1.0.4
git clone -b 6.2.2 https://github.com/vmware/nsxraml.git
