### ISSUE TITLE
Idempotency problem with nsx_deploy_ova

### ISSUE THREAD

**Issue by afewell** [vmware/nsxansible#43]
Hi, I ran a play which only included nsx_deploy_ova, the first run it transferred the ova file to vcenter successfully, but unable to boot because I didnt have the right hardware spec on the esxi host. 

I fixed the hardware issue, but when I reran the play it recognizes the nsxmanager vm is already present in vcenter but cannot start do to API error "A VM with the name nsxmanager-01a was already present, but the API did not respond". At the time I got this error, I was able to go directly to vcenter and power on the nsxmanager without error. 

Next I deleted the nsxmanager vm from vcenter and re-ran the play, and it ran successfully. While this should be replicated for confirmation, it appears that if the first play run transfers the ova to vcenter but cannot power on the vm for some reason, subsequent re-runs of the play will not power on the VM even if the underlying error is corrected.

**Comment by yasensim** [comment]
hi @afewell , it is expected behaviour in the current implementation. I am working on a new way to deploy ova in order to remove the dependancy of ovftool. It sounds as a good proposal and I can consider to add the logic to power on the VM if it is there and the API doesn't respond. I will keep you posted.

**Comment by yfauser** [comment]
Closing this Issue as the new OVA Module will solve it in future

**Comment by afewell** [comment]
Thanks so much!
