### ISSUE TITLE
OVF Manager internal error when trying to create controller cluster

### ISSUE THREAD

**Issue by devzero0** [vmware/nsxansible#48]
Using the devel branch. Controller deployment fails and vSphere displays the error "OVF Manager internal error. For more details, refer to the rootCauseString or the VC logs". Manager log on NSX Manager includes:

```
ERROR taskScheduler-6 OvfManagerImpl:139 - Failed to create OVF import spec.
(vmodl.fault.InvalidType) {
   faultCause = null,
   faultMessage = null,
   argument = ManagedObjectReference
}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        ...
```

**Comment by yfauser** [comment]
@yasensim 

Hi @devzero0, the last commit to nsx_controllers.py was last June, and Master and Devel have the same commits to this module. So, I'm assuming the controller deployment also fails when you use the Master branch? Have you tried deploying the nsx-controllers from the NSX-Manager GUI and checked if you get the same error?
Also, it might be that one of your moids passed to the nsx controllers module is 'None' instead of a correct value.

**Comment by devzero0** [comment]
You called it, I was passing some bad moids. Thanks!

**Comment by yfauser** [comment]
Gr8!
