### ISSUE TITLE
Discrepancies between nsx_edge_router documentation, error messages and implementation

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [vmware/nsxansible#50]
In the `interfaces` parameter of the `nsx_edge_router` module different names for the sub-parameters are used in the error messages, documentation and the field actually read:

readme.md  | Error Message | Actual field name
------------ |----------------|----------------
prefix_len | pfx_len       | prefix_len
if_type    | if_type       | iftype

I proposed to fix the error message for the prefix length to `prefix_len` and the implementation of the interface type to use `if_type`.

**Comment by dennis-benzinger-hybris** [comment]
Besides the two lines in in my pull request #51 `iftype` is also used in lines 118, 253 and 254.

**Comment by dennis-benzinger-hybris** [comment]
I've updated the pull request now so that it includes lines 118, 253 and 254.

**Comment by yfauser** [comment]
@dennis-benzinger-hybris Thanks! Will look into it

**Comment by yfauser** [comment]
@dennis-benzinger-hybris 

I agree that using iftype instead of if_type is inconsistent in terms of naming convention, and I'm sorry that I made this mistake. The problem I have is that iftype is used in both the ESG and DLR module and therefore changing the parameter to if_type would break other peoples existing palybooks if we change it. Therefore I would rather like to change the documentation and error message.

We are working on upstreaming the Modules to the Ansible repo, and I'm planning a major overhaul of the Modules including inline documentation, etc. soon. I will make sure we harmonize the parameters then.

Is this ok with you?

Thanks!
